# fly.toml app configuration file generated for lab1-node-late-pond-2247-red-grass-437 on 2024-01-23T18:16:08+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lab1-node-late-pond-2247-red-grass-437"
primary_region = "waw"

[build]

[http_service]
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
